// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: proto/whisper/v1/whisper.proto

package whisperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthCheckRequest is the request for checking service health
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_whisper_v1_whisper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whisper_v1_whisper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_whisper_v1_whisper_proto_rawDescGZIP(), []int{0}
}

// HealthCheckResponse contains the service health status
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status indicates if the service is healthy
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// model_loaded indicates if the Whisper model is loaded in memory
	ModelLoaded bool `protobuf:"varint,2,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`
	// model_path is the path to the loaded model
	ModelPath     string `protobuf:"bytes,3,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_whisper_v1_whisper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whisper_v1_whisper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_whisper_v1_whisper_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetModelLoaded() bool {
	if x != nil {
		return x.ModelLoaded
	}
	return false
}

func (x *HealthCheckResponse) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

// TranscribeRequest contains audio data to be transcribed
type TranscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// audio_data is the raw audio bytes (PCM 16-bit, 16kHz, mono)
	AudioData []byte `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	// language is the optional language code (e.g., "en", "es", "fr")
	// If empty, auto-detection will be used
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// sample_rate is the audio sample rate in Hz (default: 16000)
	SampleRate    int32 `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	mi := &file_proto_whisper_v1_whisper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whisper_v1_whisper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_whisper_v1_whisper_proto_rawDescGZIP(), []int{2}
}

func (x *TranscribeRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *TranscribeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TranscribeRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

// TranscribeResponse contains the transcription result
type TranscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// text is the transcribed text
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// language_detected is the detected language code
	LanguageDetected string `protobuf:"bytes,2,opt,name=language_detected,json=languageDetected,proto3" json:"language_detected,omitempty"`
	// confidence is the transcription confidence score (0.0 to 1.0)
	Confidence float32 `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// duration_ms is the processing time in milliseconds
	DurationMs    int64 `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeResponse) Reset() {
	*x = TranscribeResponse{}
	mi := &file_proto_whisper_v1_whisper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeResponse) ProtoMessage() {}

func (x *TranscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whisper_v1_whisper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeResponse.ProtoReflect.Descriptor instead.
func (*TranscribeResponse) Descriptor() ([]byte, []int) {
	return file_proto_whisper_v1_whisper_proto_rawDescGZIP(), []int{3}
}

func (x *TranscribeResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscribeResponse) GetLanguageDetected() string {
	if x != nil {
		return x.LanguageDetected
	}
	return ""
}

func (x *TranscribeResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TranscribeResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_proto_whisper_v1_whisper_proto protoreflect.FileDescriptor

const file_proto_whisper_v1_whisper_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/whisper/v1/whisper.proto\x12\n" +
	"whisper.v1\"\x14\n" +
	"\x12HealthCheckRequest\"o\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fmodel_loaded\x18\x02 \x01(\bR\vmodelLoaded\x12\x1d\n" +
	"\n" +
	"model_path\x18\x03 \x01(\tR\tmodelPath\"o\n" +
	"\x11TranscribeRequest\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRate\"\x96\x01\n" +
	"\x12TranscribeResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12+\n" +
	"\x11language_detected\x18\x02 \x01(\tR\x10languageDetected\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs2\xad\x01\n" +
	"\x0eWhisperService\x12N\n" +
	"\vHealthCheck\x12\x1e.whisper.v1.HealthCheckRequest\x1a\x1f.whisper.v1.HealthCheckResponse\x12K\n" +
	"\n" +
	"Transcribe\x12\x1d.whisper.v1.TranscribeRequest\x1a\x1e.whisper.v1.TranscribeResponseB>Z<github.com/pmbstyle/alice/backend/proto/whisper/v1;whisperv1b\x06proto3"

var (
	file_proto_whisper_v1_whisper_proto_rawDescOnce sync.Once
	file_proto_whisper_v1_whisper_proto_rawDescData []byte
)

func file_proto_whisper_v1_whisper_proto_rawDescGZIP() []byte {
	file_proto_whisper_v1_whisper_proto_rawDescOnce.Do(func() {
		file_proto_whisper_v1_whisper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_whisper_v1_whisper_proto_rawDesc), len(file_proto_whisper_v1_whisper_proto_rawDesc)))
	})
	return file_proto_whisper_v1_whisper_proto_rawDescData
}

var file_proto_whisper_v1_whisper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_whisper_v1_whisper_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),  // 0: whisper.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 1: whisper.v1.HealthCheckResponse
	(*TranscribeRequest)(nil),   // 2: whisper.v1.TranscribeRequest
	(*TranscribeResponse)(nil),  // 3: whisper.v1.TranscribeResponse
}
var file_proto_whisper_v1_whisper_proto_depIdxs = []int32{
	0, // 0: whisper.v1.WhisperService.HealthCheck:input_type -> whisper.v1.HealthCheckRequest
	2, // 1: whisper.v1.WhisperService.Transcribe:input_type -> whisper.v1.TranscribeRequest
	1, // 2: whisper.v1.WhisperService.HealthCheck:output_type -> whisper.v1.HealthCheckResponse
	3, // 3: whisper.v1.WhisperService.Transcribe:output_type -> whisper.v1.TranscribeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_whisper_v1_whisper_proto_init() }
func file_proto_whisper_v1_whisper_proto_init() {
	if File_proto_whisper_v1_whisper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_whisper_v1_whisper_proto_rawDesc), len(file_proto_whisper_v1_whisper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_whisper_v1_whisper_proto_goTypes,
		DependencyIndexes: file_proto_whisper_v1_whisper_proto_depIdxs,
		MessageInfos:      file_proto_whisper_v1_whisper_proto_msgTypes,
	}.Build()
	File_proto_whisper_v1_whisper_proto = out.File
	file_proto_whisper_v1_whisper_proto_goTypes = nil
	file_proto_whisper_v1_whisper_proto_depIdxs = nil
}
