// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: proto/piper/v1/piper.proto

package piperv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PiperService_HealthCheck_FullMethodName = "/piper.v1.PiperService/HealthCheck"
	PiperService_Synthesize_FullMethodName  = "/piper.v1.PiperService/Synthesize"
	PiperService_GetVoices_FullMethodName   = "/piper.v1.PiperService/GetVoices"
)

// PiperServiceClient is the client API for PiperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PiperService provides text-to-speech synthesis via gRPC
type PiperServiceClient interface {
	// HealthCheck verifies the service is running and models are loaded
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Synthesize converts text to speech audio
	Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (*SynthesizeResponse, error)
	// GetVoices returns the list of available voice models
	GetVoices(ctx context.Context, in *GetVoicesRequest, opts ...grpc.CallOption) (*GetVoicesResponse, error)
}

type piperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPiperServiceClient(cc grpc.ClientConnInterface) PiperServiceClient {
	return &piperServiceClient{cc}
}

func (c *piperServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PiperService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *piperServiceClient) Synthesize(ctx context.Context, in *SynthesizeRequest, opts ...grpc.CallOption) (*SynthesizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SynthesizeResponse)
	err := c.cc.Invoke(ctx, PiperService_Synthesize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *piperServiceClient) GetVoices(ctx context.Context, in *GetVoicesRequest, opts ...grpc.CallOption) (*GetVoicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVoicesResponse)
	err := c.cc.Invoke(ctx, PiperService_GetVoices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PiperServiceServer is the server API for PiperService service.
// All implementations must embed UnimplementedPiperServiceServer
// for forward compatibility.
//
// PiperService provides text-to-speech synthesis via gRPC
type PiperServiceServer interface {
	// HealthCheck verifies the service is running and models are loaded
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Synthesize converts text to speech audio
	Synthesize(context.Context, *SynthesizeRequest) (*SynthesizeResponse, error)
	// GetVoices returns the list of available voice models
	GetVoices(context.Context, *GetVoicesRequest) (*GetVoicesResponse, error)
	mustEmbedUnimplementedPiperServiceServer()
}

// UnimplementedPiperServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPiperServiceServer struct{}

func (UnimplementedPiperServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPiperServiceServer) Synthesize(context.Context, *SynthesizeRequest) (*SynthesizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Synthesize not implemented")
}
func (UnimplementedPiperServiceServer) GetVoices(context.Context, *GetVoicesRequest) (*GetVoicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVoices not implemented")
}
func (UnimplementedPiperServiceServer) mustEmbedUnimplementedPiperServiceServer() {}
func (UnimplementedPiperServiceServer) testEmbeddedByValue()                      {}

// UnsafePiperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PiperServiceServer will
// result in compilation errors.
type UnsafePiperServiceServer interface {
	mustEmbedUnimplementedPiperServiceServer()
}

func RegisterPiperServiceServer(s grpc.ServiceRegistrar, srv PiperServiceServer) {
	// If the following call panics, it indicates UnimplementedPiperServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PiperService_ServiceDesc, srv)
}

func _PiperService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiperServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiperService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiperServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PiperService_Synthesize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynthesizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiperServiceServer).Synthesize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiperService_Synthesize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiperServiceServer).Synthesize(ctx, req.(*SynthesizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PiperService_GetVoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVoicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiperServiceServer).GetVoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiperService_GetVoices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiperServiceServer).GetVoices(ctx, req.(*GetVoicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PiperService_ServiceDesc is the grpc.ServiceDesc for PiperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PiperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "piper.v1.PiperService",
	HandlerType: (*PiperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _PiperService_HealthCheck_Handler,
		},
		{
			MethodName: "Synthesize",
			Handler:    _PiperService_Synthesize_Handler,
		},
		{
			MethodName: "GetVoices",
			Handler:    _PiperService_GetVoices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/piper/v1/piper.proto",
}
