// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: proto/piper/v1/piper.proto

package piperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthCheckRequest is empty as no parameters are needed
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_piper_v1_piper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_piper_v1_piper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_piper_v1_piper_proto_rawDescGZIP(), []int{0}
}

// HealthCheckResponse contains service status information
type HealthCheckResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                          // "healthy" or "unhealthy"
	ModelLoaded     bool                   `protobuf:"varint,2,opt,name=model_loaded,json=modelLoaded,proto3" json:"model_loaded,omitempty"`            // True if at least one model is available
	AvailableVoices []string               `protobuf:"bytes,3,rep,name=available_voices,json=availableVoices,proto3" json:"available_voices,omitempty"` // List of loaded voice names
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_piper_v1_piper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_piper_v1_piper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_piper_v1_piper_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetModelLoaded() bool {
	if x != nil {
		return x.ModelLoaded
	}
	return false
}

func (x *HealthCheckResponse) GetAvailableVoices() []string {
	if x != nil {
		return x.AvailableVoices
	}
	return nil
}

// SynthesizeRequest contains text and voice parameters for synthesis
type SynthesizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`     // Text to synthesize (required)
	Voice         string                 `protobuf:"bytes,2,opt,name=voice,proto3" json:"voice,omitempty"`   // Voice model name (e.g., "en_US-amy-medium")
	Speed         float32                `protobuf:"fixed32,3,opt,name=speed,proto3" json:"speed,omitempty"` // Playback speed multiplier (1.0 = normal, default)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeRequest) Reset() {
	*x = SynthesizeRequest{}
	mi := &file_proto_piper_v1_piper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeRequest) ProtoMessage() {}

func (x *SynthesizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_piper_v1_piper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeRequest.ProtoReflect.Descriptor instead.
func (*SynthesizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_piper_v1_piper_proto_rawDescGZIP(), []int{2}
}

func (x *SynthesizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeRequest) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *SynthesizeRequest) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

// SynthesizeResponse contains the generated audio data
type SynthesizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`     // WAV format audio bytes
	SampleRate    int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // Sample rate in Hz (typically 22050)
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // Processing duration in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeResponse) Reset() {
	*x = SynthesizeResponse{}
	mi := &file_proto_piper_v1_piper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeResponse) ProtoMessage() {}

func (x *SynthesizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_piper_v1_piper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeResponse.ProtoReflect.Descriptor instead.
func (*SynthesizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_piper_v1_piper_proto_rawDescGZIP(), []int{3}
}

func (x *SynthesizeResponse) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *SynthesizeResponse) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *SynthesizeResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// GetVoicesRequest is empty as no parameters are needed
type GetVoicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVoicesRequest) Reset() {
	*x = GetVoicesRequest{}
	mi := &file_proto_piper_v1_piper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoicesRequest) ProtoMessage() {}

func (x *GetVoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_piper_v1_piper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoicesRequest.ProtoReflect.Descriptor instead.
func (*GetVoicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_piper_v1_piper_proto_rawDescGZIP(), []int{4}
}

// Voice represents metadata for a single voice model
type Voice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                // Voice identifier (e.g., "en_US-amy-medium")
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`                        // Language code (e.g., "en-US", "es-MX")
	Gender        string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`                            // "male" or "female"
	Quality       string                 `protobuf:"bytes,4,opt,name=quality,proto3" json:"quality,omitempty"`                          // "x_low", "low", "medium", "high"
	SampleRate    int32                  `protobuf:"varint,5,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // Sample rate in Hz
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`                  // Human-readable description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Voice) Reset() {
	*x = Voice{}
	mi := &file_proto_piper_v1_piper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Voice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Voice) ProtoMessage() {}

func (x *Voice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_piper_v1_piper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Voice.ProtoReflect.Descriptor instead.
func (*Voice) Descriptor() ([]byte, []int) {
	return file_proto_piper_v1_piper_proto_rawDescGZIP(), []int{5}
}

func (x *Voice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Voice) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Voice) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Voice) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *Voice) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *Voice) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// GetVoicesResponse contains the list of available voices
type GetVoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voices        []*Voice               `protobuf:"bytes,1,rep,name=voices,proto3" json:"voices,omitempty"` // List of all available voice models
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVoicesResponse) Reset() {
	*x = GetVoicesResponse{}
	mi := &file_proto_piper_v1_piper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoicesResponse) ProtoMessage() {}

func (x *GetVoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_piper_v1_piper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoicesResponse.ProtoReflect.Descriptor instead.
func (*GetVoicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_piper_v1_piper_proto_rawDescGZIP(), []int{6}
}

func (x *GetVoicesResponse) GetVoices() []*Voice {
	if x != nil {
		return x.Voices
	}
	return nil
}

var File_proto_piper_v1_piper_proto protoreflect.FileDescriptor

const file_proto_piper_v1_piper_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/piper/v1/piper.proto\x12\bpiper.v1\"\x14\n" +
	"\x12HealthCheckRequest\"{\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fmodel_loaded\x18\x02 \x01(\bR\vmodelLoaded\x12)\n" +
	"\x10available_voices\x18\x03 \x03(\tR\x0favailableVoices\"S\n" +
	"\x11SynthesizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05voice\x18\x02 \x01(\tR\x05voice\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x02R\x05speed\"u\n" +
	"\x12SynthesizeResponse\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\"\x12\n" +
	"\x10GetVoicesRequest\"\xac\x01\n" +
	"\x05Voice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12\x18\n" +
	"\aquality\x18\x04 \x01(\tR\aquality\x12\x1f\n" +
	"\vsample_rate\x18\x05 \x01(\x05R\n" +
	"sampleRate\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"<\n" +
	"\x11GetVoicesResponse\x12'\n" +
	"\x06voices\x18\x01 \x03(\v2\x0f.piper.v1.VoiceR\x06voices2\xe9\x01\n" +
	"\fPiperService\x12J\n" +
	"\vHealthCheck\x12\x1c.piper.v1.HealthCheckRequest\x1a\x1d.piper.v1.HealthCheckResponse\x12G\n" +
	"\n" +
	"Synthesize\x12\x1b.piper.v1.SynthesizeRequest\x1a\x1c.piper.v1.SynthesizeResponse\x12D\n" +
	"\tGetVoices\x12\x1a.piper.v1.GetVoicesRequest\x1a\x1b.piper.v1.GetVoicesResponseB:Z8github.com/pmbstyle/alice/backend/proto/piper/v1;piperv1b\x06proto3"

var (
	file_proto_piper_v1_piper_proto_rawDescOnce sync.Once
	file_proto_piper_v1_piper_proto_rawDescData []byte
)

func file_proto_piper_v1_piper_proto_rawDescGZIP() []byte {
	file_proto_piper_v1_piper_proto_rawDescOnce.Do(func() {
		file_proto_piper_v1_piper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_piper_v1_piper_proto_rawDesc), len(file_proto_piper_v1_piper_proto_rawDesc)))
	})
	return file_proto_piper_v1_piper_proto_rawDescData
}

var file_proto_piper_v1_piper_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_piper_v1_piper_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),  // 0: piper.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 1: piper.v1.HealthCheckResponse
	(*SynthesizeRequest)(nil),   // 2: piper.v1.SynthesizeRequest
	(*SynthesizeResponse)(nil),  // 3: piper.v1.SynthesizeResponse
	(*GetVoicesRequest)(nil),    // 4: piper.v1.GetVoicesRequest
	(*Voice)(nil),               // 5: piper.v1.Voice
	(*GetVoicesResponse)(nil),   // 6: piper.v1.GetVoicesResponse
}
var file_proto_piper_v1_piper_proto_depIdxs = []int32{
	5, // 0: piper.v1.GetVoicesResponse.voices:type_name -> piper.v1.Voice
	0, // 1: piper.v1.PiperService.HealthCheck:input_type -> piper.v1.HealthCheckRequest
	2, // 2: piper.v1.PiperService.Synthesize:input_type -> piper.v1.SynthesizeRequest
	4, // 3: piper.v1.PiperService.GetVoices:input_type -> piper.v1.GetVoicesRequest
	1, // 4: piper.v1.PiperService.HealthCheck:output_type -> piper.v1.HealthCheckResponse
	3, // 5: piper.v1.PiperService.Synthesize:output_type -> piper.v1.SynthesizeResponse
	6, // 6: piper.v1.PiperService.GetVoices:output_type -> piper.v1.GetVoicesResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_piper_v1_piper_proto_init() }
func file_proto_piper_v1_piper_proto_init() {
	if File_proto_piper_v1_piper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_piper_v1_piper_proto_rawDesc), len(file_proto_piper_v1_piper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_piper_v1_piper_proto_goTypes,
		DependencyIndexes: file_proto_piper_v1_piper_proto_depIdxs,
		MessageInfos:      file_proto_piper_v1_piper_proto_msgTypes,
	}.Build()
	File_proto_piper_v1_piper_proto = out.File
	file_proto_piper_v1_piper_proto_goTypes = nil
	file_proto_piper_v1_piper_proto_depIdxs = nil
}
